import * as esbuild from "esbuild";
import { execFile } from "node:child_process";
import { mkdir, readFile, rm, writeFile } from "node:fs/promises";
import { promisify } from "node:util";

const execFileAsync = promisify(execFile);
const tempDir = ".ui-build";
const generatedDir = "src/ui/generated";

await rm(tempDir, { recursive: true, force: true });
await mkdir(tempDir, { recursive: true });
await mkdir(generatedDir, { recursive: true });

await esbuild.build({
  entryPoints: ["src/ui/app.tsx"],
  bundle: true,
  platform: "browser",
  format: "iife",
  target: ["es2020"],
  minify: true,
  define: {
    "process.env.NODE_ENV": '"production"',
  },
  outfile: `${tempDir}/app.js`,
});

await execFileAsync(process.execPath, [
  "node_modules/tailwindcss/lib/cli.js",
  "-c",
  "tailwind.config.cjs",
  "-i",
  "src/ui/app.css",
  "-o",
  `${tempDir}/app.css`,
  "--minify",
]);

const script = escapeScript(await readFile(`${tempDir}/app.js`, "utf8"));
const styles = await readFile(`${tempDir}/app.css`, "utf8");

await writeFile(
  `${generatedDir}/assets.ts`,
  `// Generated by scripts/build-ui.mjs. Do not edit by hand.\nexport const APP_SCRIPT = ${JSON.stringify(script)};\nexport const APP_STYLES = ${JSON.stringify(styles)};\n`,
);

await rm(tempDir, { recursive: true, force: true });

function escapeScript(value) {
  return value.replace(/<\/script/gi, "<\\/script").replace(/<!--/g, "<\\!--").replace(/\u2028/g, "\\u2028").replace(/\u2029/g, "\\u2029");
}
